"use client";
import {useState} from "react";

const phone="543853034509";
const whatsapp=`https://wa.me/${phone}?text=${encodeURIComponent("Hola Happy Deco, quiero consultar por una ambientación")}`;
const proposals=[
 {name:"Express",tag:"Íntima",image:"/images/ambientacion-03.jpg",desc:"Una ambientación simple y cuidada, ideal para festejos íntimos y espacios pequeños.",meta:"Hasta 20 personas",items:["Panel con funda temática","Mesa principal y armado decorativo","Globos en paleta combinada","Nombre y personaje impreso"]},
 {name:"Minimalista",tag:"Sutil",image:"/images/ambientacion-04.jpg",desc:"Un único foco visual, delicado y personalizado para casas, departamentos o salones pequeños.",meta:"Ideal para 30 personas",items:["Panel de fondo","Mesa principal con mantel","Guirnalda y globos temáticos","Gráfica, nombre y número en neón"]},
 {name:"Clásica",tag:"Completa",image:"/images/evento-real-05.jpg",desc:"Una composición envolvente con más mobiliario y presencia visual.",meta:"Hasta 40 personas",items:["Dos paneles con fundas","Tres mesas decorativas","Globos y gráfica temática","Nombre y alfombra decorativa"]},
 {name:"Intermedia",tag:"Especial",image:"/images/ambientacion-06.jpg",desc:"Una puesta armoniosa para espacios medianos, con arco orgánico y distintos planos.",meta:"30 a 50 personas",items:["Tres paneles","Mesa principal y tres accesorias","Alfombra y arco orgánico","Floreros, nombre, personaje y neón"]},
 {name:"Premium",tag:"Distinguida",image:"/images/evento-real-07.jpg",desc:"Una propuesta completa y de alto impacto, pensada para celebraciones que buscan destacarse.",meta:"Desde 3 × 3 m",items:["Cuatro paneles","Mesa principal y cinco accesorias","Arco orgánico de alto impacto","Alfombra, floreros, gráfica y neón"]},
 {name:"Exclusiva",tag:"Inolvidable",image:"/images/evento-real-08.jpg",desc:"Una ambientación amplia con tarima, panel 3D e iluminación decorativa.",meta:"80 a 100 personas",items:["Cuatro paneles y panel 3D","Tarima y siete mesas","Globos, alfombra y floreros","Gráfica, neón e iluminación"]},
 {name:"Escenográfica 3×3",tag:"Inmersiva",image:"/images/evento-real-09.jpg",desc:"Una escena temática inmersiva que transforma por completo un sector del evento.",meta:"Armado estimado: 3 a 4 h",items:["Telón ambientado de 3 × 3 m","Panel 3D y cinco mesas","Elementos inmersivos y arco orgánico","Gráfica, neón e iluminación"]},
 {name:"Escenográfica 6×3",tag:"Gran escala",image:"/images/evento-real-10.jpg",desc:"Mayor desarrollo visual para eventos medianos a grandes.",meta:"Armado estimado: 3 a 4 h",items:["Telón ambientado de 6 × 3 m","Panel 3D y siete mesas","Elementos inmersivos y arco orgánico","Gráfica, neón e iluminación"]},
 {name:"Escenográfica 10×3",tag:"Impactante",image:"/images/evento-real-11.jpg",desc:"La propuesta más completa, creada para celebraciones centrales y espacios de gran escala.",meta:"Armado estimado: 5 a 6 h",items:["Telón ambientado de 10 × 3 m","Panel 3D y trece mesas","Sector de exhibición y piso sublimado","Elementos inmersivos, neón e iluminación"]}
];
const gallery=["05","07","08","09","10","11"];
const process=[{n:"01",t:"Nos contás tu idea",d:"Conversamos sobre la celebración, la temática, los colores y el espacio disponible."},{n:"02",t:"Diseñamos la propuesta",d:"Elegimos la composición que mejor acompaña el evento y la personalizamos."},{n:"03",t:"Preparamos cada detalle",d:"Coordinamos los elementos, la gráfica, los globos y el mobiliario de la puesta."},{n:"04",t:"Montamos la ambientación",d:"Realizamos el armado para transformar el espacio antes del momento especial."}];

export default function Home(){
 const [open,setOpen]=useState<number|null>(null);
 return <main>
  <header className="site-header"><a className="logo" href="#inicio" aria-label="Happy Deco, inicio">Happy <span>Deco</span></a><nav aria-label="Navegación principal"><a href="#nosotras">Nosotras</a><a href="#propuestas">Propuestas</a><a href="#galeria">Galería</a><a href="#proceso">Cómo trabajamos</a></nav><a className="mini-cta" href={whatsapp} target="_blank" rel="noreferrer">Consultar</a></header>
  <section className="hero" id="inicio"><div className="hero-copy"><p className="eyebrow">Ambientaciones con identidad</p><h1>Magia en<br/><em>cada evento.</em></h1><p className="lead">Creamos escenarios que transforman espacios y hacen que cada celebración se sienta verdaderamente especial.</p><div className="hero-actions"><a className="button primary" href="#propuestas">Conocé las propuestas</a><a className="button ghost" href={whatsapp} target="_blank" rel="noreferrer">Escribinos por WhatsApp</a></div></div><div className="hero-collage" aria-label="Ambientaciones realizadas por Happy Deco"><figure className="photo-main"><img src="/images/evento-real-11.jpg" alt="Ambientación amplia en tonos pastel"/></figure><figure className="photo-small"><img src="/images/evento-real-07.jpg" alt="Ambientación de cumpleaños en tonos rosa y dorado"/></figure><div className="seal"><strong>Desde</strong><span>2022</span></div></div><span className="doodle d1">✦</span><span className="doodle d2">⌁</span></section>

  <section className="story" id="nosotras"><div className="story-kicker">Una historia compartida</div><div className="story-grid"><h2>Dos miradas,<br/>una misma <span>pasión.</span></h2><div><p className="story-lead">Happy Deco nació en 2022 de la mano de Xime y Cati, madre e hija, unidas por la sensibilidad, la creatividad y el deseo de hacer inolvidable cada encuentro.</p><p>Diseñamos ambientaciones integrales que cuentan historias. Escuchamos cada idea, cuidamos los detalles y adaptamos cada propuesta para que el resultado se sienta propio.</p><div className="values"><span>Creatividad</span><span>Cercanía</span><span>Detalle</span></div></div></div></section>

  <section className="proposals" id="propuestas"><div className="section-heading"><div><p className="eyebrow">Nuestras propuestas</p><h2>La escala justa<br/>para tu celebración.</h2></div><p>Desde encuentros íntimos hasta grandes escenografías. Todas las propuestas se personalizan en temática y colores, y se adaptan al espacio disponible.</p></div><div className="proposal-grid">{proposals.map((p,i)=><article className={`proposal-card c${i%5}`} key={p.name}><div className="proposal-photo"><img src={p.image} alt={`Ambientación de la propuesta ${p.name}`}/><span>{p.tag}</span></div><div className="proposal-copy"><p className="proposal-index">0{i+1}</p><h3>{p.name}</h3><p>{p.desc}</p><small>{p.meta}</small><button onClick={()=>setOpen(i)} aria-label={`Ver detalles de ${p.name}`}>Ver qué incluye <b>→</b></button></div></article>)}</div><p className="catalog-note">Pastelería y papelería creativa no incluidas. Las imágenes son ilustrativas y pueden presentar variaciones según la temática.</p></section>

  <section className="gallery" id="galeria"><div className="gallery-head"><div><p className="eyebrow">Momentos transformados</p><h2>Cada evento,<br/>un universo propio.</h2></div><p>Temáticas, colores, mobiliarios y escalas diferentes. Una misma atención por lo que hace único a cada festejo.</p></div><div className="gallery-grid">{gallery.map((n,i)=><figure className={`gallery-item g${i+1}`} key={n}><img src={`/images/evento-real-${n}.jpg`} alt={`Ambientación realizada por Happy Deco ${i+1}`} loading="lazy"/></figure>)}</div></section>

  <section className="process" id="proceso"><div className="process-intro"><p className="eyebrow">Cómo trabajamos</p><h2>De una idea<br/>a un momento<br/><span>inolvidable.</span></h2><p>Un recorrido cercano y cuidado, pensado para que puedas disfrutar del proceso tanto como del resultado.</p></div><ol>{process.map(s=><li key={s.n}><span>{s.n}</span><div><h3>{s.t}</h3><p>{s.d}</p></div></li>)}</ol></section>

  <section className="shop-window"><div className="window-image"><img src="/images/vidriera-dia-nino.jpg" alt="Vidriera comercial decorada para el Día del Niño"/></div><div className="window-copy"><p className="eyebrow">También para comercios</p><h2>Vidrieras que<br/>atraen miradas.</h2><p>Creamos campañas estacionales para transformar vidrieras, destacar productos y conectar cada negocio con fechas especiales.</p><a className="button dark" href="https://happy-deco-vidrieras.netlify.app" target="_blank" rel="noreferrer">Conocé las propuestas para vidrieras <span>↗</span></a></div></section>

  <section className="contact" id="contacto"><p className="eyebrow">Empecemos a imaginar</p><h2>Tu próximo evento<br/>puede sentirse <em>así.</em></h2><p>Contanos qué estás celebrando, cuándo y en qué espacio. Te ayudamos a encontrar la propuesta que mejor acompañe ese momento.</p><a className="button contact-button" href={whatsapp} target="_blank" rel="noreferrer">Consultar por WhatsApp</a><div className="contact-links"><a href="tel:+543853034509">385 303-4509</a><a href="mailto:happydecoar@gmail.com">happydecoar@gmail.com</a><a href="https://instagram.com/happydecoar" target="_blank" rel="noreferrer">@happydecoar</a><span>Santiago del Estero, Argentina</span></div></section>
  <footer><a className="logo" href="#inicio">Happy <span>Deco</span></a><p>Magia en cada evento.</p><p>© 2026 Happy Deco</p></footer>
  <a className="floating-wa" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Consultar por WhatsApp">WhatsApp</a>
  {open!==null&&<div className="modal-backdrop" onClick={()=>setOpen(null)} role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setOpen(null)} aria-label="Cerrar">×</button><div className="modal-photo"><img src={proposals[open].image} alt={`Ambientación ${proposals[open].name}`}/></div><div className="modal-body"><p className="eyebrow">Propuesta Happy Deco</p><h2 id="modal-title">{proposals[open].name}</h2><p>{proposals[open].desc}</p><h3>Incluye</h3><ul>{proposals[open].items.map(x=><li key={x}>{x}</li>)}</ul><p className="modal-meta">{proposals[open].meta}</p><a className="button primary" href={`https://wa.me/${phone}?text=${encodeURIComponent(`Hola Happy Deco, quiero consultar por la propuesta ${proposals[open].name}`)}`} target="_blank" rel="noreferrer">Consultar esta propuesta</a></div></section></div>}
 </main>
}
